name: 'Dependency Review'
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  enforce-dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@cc4f6536e38d1126c5e3b0683d469a14f23bfea4 # v3